In [10]:
print "Starting..."

%matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import FlorenceUtils # Helper functions
import scipy.io
from itertools import product
from matplotlib.patches import RegularPolygon
import seaborn as sns

print "Done importing"

Starting...
Using matplotlib backend: Qt5Agg
Done importing


TODO: Make the largest error function work
TODO: Revert the function so tiles gets de-selected also
TODO: General aethetics

# NB! curves.p has the wrong curves! 

In [2]:

data = FlorenceUtils.load_arm1_data("curves_new.p")


In [3]:
def find_largest_error(data, organ, log_array):
    
    """Function to return the largest array for a given organ for a 
    given set of removed time points given by the @log_array"""
    
    if organ == 'WB':
        
        do_wb = True
        
    else:
        
        do_wb = False
    
    for i in range(4):
        
        print "got here"
        
        t_vec = data['Time'][i]
        a_vec = data[organ][i]
        
        print FlorenceUtils.return_diff_full_and_reduced(t_vec, a_vec, log_array, is_wb=do_wb)
        

In [4]:

log_array = np.array([1,0,0,1,1,1])

print log_array

print find_largest_error(data, "WB", log_array)

[1 0 0 1 1 1]
got here
4
-0.0102333778642
got here
4
-0.0113828521018
got here
4
-0.0107935176946
got here
4
-0.00823771171141
None


In [5]:
# Test area for the lowest function
error_vector = np.ones(4)
cut_vec = np.array([0,1,1,1,1,1])

cut_matrix = np.array(
    [[1,1,1,1,1,1],
    [1,1,1,1,1,1],
    [1,1,1,1,1,1],
    [1,1,1,1,1,1],
    [1,1,1,1,1,1],
    [1,1,1,1,1,1],
    [1,1,1,1,1,1],
    [0,0,0,1,1,1]],)

i = 0

print cut_matrix[-1,:]

for i in range(4):

    t_vec = data['Time'][i]
    a_vec = data['Liver'][i]

    error_vector[i] = FlorenceUtils.return_diff_full_and_reduced(t_vec, a_vec, cut_vec)
    print  FlorenceUtils.return_diff_full_and_reduced(t_vec, a_vec, cut_vec)
    
print error_vector
print max(np.min(error_vector), np.max(error_vector), key = abs)

[0 0 0 1 1 1]
0.000766441691321
0.000583522722055
5.07821221172e-05
0.000171551196964
[  7.66441691e-04   5.83522722e-04   5.07821221e-05   1.71551197e-04]
0.000766441691321


In [19]:
def on_click(event):
    
    #print "pressed"
    
    #print len(polygons)
        
    if polygon_draw.contains_point((event.x, event.y)):
        
        # Snippet for making the aestetics of the heatmap
        
        ax = sns.heatmap(cut_matrix)
    #    print "fdsf"
    
    for i in range(0, 36): # TODO: Remove magic number...
                
        curr_pol = polygons[i]
                
        if curr_pol.contains_point((event.x, event.y)):
            
            curr_pol.set_facecolor('#404040')
                
            curr_pol_ind = poly_inds[i]
            
            logical_back[curr_pol_ind[1], curr_pol_ind[0]] = 1
            
            #print logical_back
              
            
                
                
    fig.canvas.draw()

In [20]:
# Now comes the hard part, making the GUI quick, fast and simple for use...

size_factor_x = 20
size_factor_y = 20

num_row = 6
num_cols = 6

fig = plt.figure(figsize = ((size_factor_y + 2) / 4., (size_factor_x + 2) / 3.))

ax = fig.add_axes((0.05, 0.05, 0.9, 0.9), aspect = 'equal', frameon = False,
    xlim = (-0.05, size_factor_y + 0.05),
    ylim = (-0.05, size_factor_x + 0.05))

for axies in (ax.xaxis, ax.yaxis):

    axies.set_major_formatter(plt.NullFormatter())
    axies.set_major_formatter(plt.NullFormatter())
    

polygon_draw = plt.Polygon([[15,7], [15,11], [17,11], [17,7],[15,7]], closed = True, fc = '#202020')

polygon_draw.set_picker(True)

ax.add_patch(polygon_draw)

x_0 = 2
y_0 = 7
L = 2 
S = 2

x_ind = 0
y_ind = 0

polygons = []
poly_inds = []

glob_time = ['2 h', '4 h', '8 h', '24 h', '96 h', '168 h']

for i in range(0,num_cols):
    
    for j in range(0, num_row):

        polygon_1 = plt.Polygon([[x_0, y_0],
                [x_0,y_0 + L],
                [x_0 + L,y_0 + L],
                [x_0 + L,y_0], 
                [x_0,y_0]], 
                fc = 'white',
                ec = 'black')

        y_0 = y_0 + S

        ax.add_patch(polygon_1)
        polygons.append(polygon_1)

        poly_ind = (x_ind, y_ind)

        poly_inds.append(poly_ind)

        y_ind = y_ind + 1

    x_ind = x_ind + 1

    y_0 = 7
    y_ind = 0
    x_0 = x_0 + S

text_hrs_space = 1.8

for num_time in range(0, len(glob_time)):

    ax.text(2.7 + num_time*text_hrs_space,num_row*3.2 + 0.2, glob_time[num_time])

logical_back = np.zeros([num_row, num_cols])

foo = fig.canvas.mpl_connect('button_press_event', on_click)

#plt.show()
#plt.ion()

In [ ]:
plt.clf